name: object_detection_CNN
channels:
- defaults
dependencies:
- backports=1.0=py36hfa02d7e_1
- backports.weakref=1.0rc1=py36_0
- bleach=1.5.0=py36_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.7.27.1=py36h8b7b77e_0
- cycler=0.10.0=py36h93f1223_0
- dbus=1.10.22=h3b5a359_0
- decorator=4.1.2=py36hd076ac8_0
- entrypoints=0.2.3=py36h1aec115_2
- expat=2.2.4=hc00ebd1_1
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=h52ed37b_0
- glib=2.53.6=hc861d11_1
- gmp=6.1.2=hb3b607b_0
- gst-plugins-base=1.12.2=he3457e5_0
- gstreamer=1.12.2=h4f93127_0
- html5lib=0.9999999=py36_0
- icu=58.2=h211956c_0
- intel-openmp=2018.0.0=h15fc484_7
- ipykernel=4.6.1=py36hbf841aa_0
- ipython=6.1.0=py36hc72a948_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.0.0=py36h7b55c3a_0
- jedi=0.10.2=py36h552def0_0
- jinja2=2.9.6=py36h489bce4_1
- jpeg=9b=habf39ab_1
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36h9896ce5_0
- jupyter_client=5.1.0=py36h614e9ea_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.3.0=py36h357a921_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=h4deb6c0_3
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libpng=1.6.32=hda9c8bc_2
- libprotobuf=3.4.0=0
- libsodium=1.0.13=h31c71d8_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- libxcb=1.12=he6ee5dd_2
- libxml2=2.9.4=h6b072ca_5
- markdown=2.6.9=py36_0
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.0.2=py36h2acb4ad_1
- mistune=0.7.4=py36hbab8784_0
- mkl=2018.0.0=hb491cac_4
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- ncurses=6.0=h06874d7_1
- notebook=5.0.0=py36h0b20546_2
- numpy=1.13.3=py36ha12f23b_0
- openssl=1.0.2l=h9d1a558_3
- pandas=0.20.3=py36h842e28d_2
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- pcre=8.41=hc71a17e_0
- pexpect=4.2.1=py36h3b9d41b_0
- pickleshare=0.7.4=py36h63277f8_0
- pip=9.0.1=py36h8ec8b28_3
- prompt_toolkit=1.0.15=py36h17d85b1_0
- protobuf=3.4.0=py36_0
- ptyprocess=0.5.2=py36h69acd42_0
- pygments=2.2.0=py36h0d3125c_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- python=3.6.3=hcad60d5_0
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2017.2=py36hc2ccc2a_1
- pyyaml=3.12=py36hafb9ca4_1
- pyzmq=16.0.2=py36h3b0cf96_2
- qt=5.6.2=h974d657_12
- qtconsole=4.3.1=py36h8f73b5b_0
- readline=7.0=hac23ff0_3
- scikit-learn=0.19.0=py36h97ac459_2
- scipy=0.19.1=py36h9976243_3
- setuptools=36.5.0=py36he42e2e1_0
- simplegeneric=0.8.1=py36h2cb9092_0
- sip=4.18.1=py36h51ed4ed_2
- six=1.10.0=py36hcac75e4_1
- sqlite=3.20.1=h6d8b0f3_1
- tensorflow=1.3.0=0
- tensorflow-base=1.3.0=py36h5293eaa_1
- tensorflow-tensorboard=0.1.5=py36_0
- terminado=0.6=py36ha25a19f_0
- testpath=0.3.1=py36h8cadb63_0
- tk=8.6.7=h5979e9b_1
- tornado=4.5.2=py36h1283b2a_0
- tqdm=4.11.2=py36_0
- traitlets=4.3.2=py36h674d592_0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- werkzeug=0.12.2=py36hc703753_0
- wheel=0.29.0=py36he7f4e38_1
- widgetsnbextension=3.0.2=py36hd01bb71_1
- xz=5.2.3=h2bcbf08_1
- yaml=0.1.7=h96e3832_1
- zeromq=4.2.2=hb0b69da_1
- zlib=1.2.11=hfbfcf68_1
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
prefix: /media/kartik_nighania/data/anaconda3/envs/object_detection_CNN

